version: "3"
services:
  contenedor_mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
        MYSQL_DATABASE: app
        MYSQL_USER: seper
        MYSQL_PASSWORD: OasBOrESteNDOMen
        MYSQL_ROOT_PASSWORD: OasBOrESteNDOMen
    volumes:
      - ./mysql:/var/lib/mysql
      - ./app.sql:/docker-entrypoint-initdb.d/app.sql
    expose:
      - 3306
    ports:
      - 3306:3306

  application:
    build: .
    container_name: web_app
    expose:
      - 80
    ports:
      - 80:80
    links:
      - contenedor_mysql
